onboarding = false

[ui]
confirm_close = false
show_agent_labels_on_pane_borders = true
sidebar_start_collapsed = true

[ui.toast]
delivery = "system"

[keys]
switch_tab = "alt+1..9"

# Bureaux : ctrl+alt+1..9, et ctrl+alt+W / ctrl+alt+S pour precedent / suivant
switch_workspace = "ctrl+alt+1..9"
previous_workspace = "ctrl+alt+w"
next_workspace = "ctrl+alt+s"

# Agents : ctrl+shift+alt+1..9, et ctrl+shift+alt+W / ctrl+shift+alt+S pour precedent / suivant
focus_agent = "ctrl+shift+alt+1..9"
previous_agent = "ctrl+shift+alt+w"
next_agent = "ctrl+shift+alt+s"


[[keys.command]] # open in a split pane
key = "prefix+y"
type = "plugin_action"
command = "ray.file-explorer.open"
description = "open file explorer"

[[keys.command]] # open in a new tab
key = "prefix+Y"
type = "plugin_action"
command = "ray.file-explorer.open-tab"
description = "open file explorer in a new tab"

[[keys.command]] # open file viewer in split
key = "prefix+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer"
description = "open file viewer in split"

[[keys.command]] # open file viewer in new tab
key = "prefix+shift+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer-tab"
description = "open file viewer in new tab"


[experimental]
kitty_graphics = true
