cursor #cad3f5
cursor_text_color #a5adcb

foreground            #cad3f5
background            #24273a
selection_foreground  #303446
selection_background  #f2d5cf
url_color             #eebebe

color0   #1e2030
color1   #e25a5a
color2   #57b23e
color3   #ffd93f
color4   #f9c4c4
color5   #744f52
color6   #eebebe
color7   #423f40
color8   #040000
color9   #ff9291
color10  #91ff72
color11  #ffdc4c
color12  #ffc6c6
color13  #ffdbdb
color14  #ffe5e5
color15  #fff9fa
