cursor #c6d0f5
cursor_text_color #a5adce

foreground            #c6d0f5
background            #303446
selection_foreground  #303446
selection_background  #ca9ee6
url_color             #babbf1

color0   #737374
color1   #e45b7c
color2   #3fb454
color3   #ffca3f
color4   #c0c1fd
color5   #ececff
color6   #babbf1
color7   #d5d5d8
color8   #c7c7cc
color9   #ff7f9e
color10  #72ff8c
color11  #ffce4c
color12  #bec0ff
color13  #ececff
color14  #e1e2ff
color15  #f9f9ff
