cursor #4c4f69
cursor_text_color #6c6f85

foreground            #4c4f69
background            #eff1f5
selection_foreground  #eff1f5
selection_background  #8839ef
url_color             #7287fd

color0   #181825
color1   #f0517a
color2   #36bd4c
color3   #ffc42c
color4   #6b82ff
color5   #d2d8ff
color6   #7287fd
color7   #434446
color8   #d1d1d7
color9   #ff7297
color10  #64ff7e
color11  #ffc83a
color12  #647cff
color13  #d2d8ff
color14  #b8c3ff
color15  #f9faff
