# Rose Pine
foreground              #e0def4
background              #191724
selection_foreground    #191724
selection_background    #c4a7e7
url_color               #9ccfd8

cursor                  #e0def4
cursor_text_color       #191724

color0  #26233a
color1  #eb6f92
color2  #31748f
color3  #f6c177
color4  #9ccfd8
color5  #c4a7e7
color6  #ebbcba
color7  #e0def4
color8  #6e6a86
color9  #eb6f92
color10 #31748f
color11 #f6c177
color12 #9ccfd8
color13 #c4a7e7
color14 #ebbcba
color15 #e0def4

active_tab_foreground   #191724
active_tab_background   #c4a7e7
active_tab_font_style   bold
inactive_tab_foreground #e0def4
inactive_tab_background #1f1d2e
tab_bar_background      #16121f
