exec-once=dbus-update-activation-environment --systemd --all
exec-once=systemctl --user start mango-session.target

# Keep clipboard content after app closes
wl-clip-persist --clipboard regular --reconnect-tries 0 &

# Watch clipboard and store history
wl-paste --type text --watch cliphist store &
