# More option see https://github.com/DreamMaoMao/mango/wiki/
source=./keybinding.conf
exec-once=dbus-update-activation-environment --systemd --all
exec-once=systemctl --user start mango-session.target

env=QT_QPA_PLATFORM,wayland
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=QT_QPA_PLATFORMTHEME,gtk3
animations=1
xkb_rules_layout=us
xkb_rules_variant=altgr-intl

# Keep clipboard content after app closes
wl-clip-persist --clipboard regular --reconnect-tries 0 &

# Watch clipboard and store history
wl-paste --type text --watch cliphist store &

scroller_structs=0
scroller_proportion_preset=0.5,0.8,1.0 
scroller_default_proportion=0.5
layer_animations=1
animation_type_open=zoom
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide
# Disable animation on DMS layers
layerrule=noanim:1,layer_name:^dms
smartgaps=0
drag_tile_to_tile=1
drag_corner=4
# GNOME apps
#
windowrule=isnoborder:1,appid:^org\.gnome\.

# Terminal apps - no borders
windowrule=isnoborder:1,appid:^org\.wezfurlong\.wezterm$
windowrule=isnoborder:1,appid:^Alacritty$
windowrule=isnoborder:1,appid:^com\.mitchellh\.ghostty$
#windowrule=isnoborder:1,appid:^kitty$

# Float DMS windows
windowrule=isfloating:1,appid:^org\.quickshell$

source=./dms/binds.conf
source=./dms/colors.conf
source=./dms/layout.conf
source=./dms/outputs.conf
