# More option see https://github.com/DreamMaoMao/mango/wiki/

source=./autostart.conf
source=./environment.conf
source=./input.conf
source=./layout.conf
source=./animations.conf
source=./rules.conf
source=./keybinding.conf
source=./dms/colors.conf
source=./dms/layout.conf
source=./dms/outputs.conf

# Vertical scroll animation on workspace switch
tag_animation_direction=0
source = ./dms/binds.conf
