setlayout=scroller
sloppyfocus=0
smartgaps=1
drag_tile_to_tile=1
drag_corner=4

# Scroller layout settings
scroller_structs=1
scroller_proportion_preset=0.5,0.8,1.0
scroller_default_proportion=0.5

# Force scroller on tag 1 at startup
tagrule=id:1,layout_name:scroller
