# GNOME apps - no borders
windowrule=isnoborder:1,appid:^org\.gnome\.

# Terminal apps - no borders
windowrule=isnoborder:1,appid:^org\.wezfurlong\.wezterm$
windowrule=isnoborder:1,appid:^Alacritty$
windowrule=isnoborder:1,appid:^com\.mitchellh\.ghostty$
#windowrule=isnoborder:1,appid:^kitty$

# Float DMS windows
windowrule=isfloating:1,appid:^org\.quickshell$

# Float apps
windowrule=isfloating:1,appid:^pavucontrol$
windowrule=isfloating:1,appid:^blueman-manager$
windowrule=isfloating:1,appid:^xdg-desktop-portal-gtk$
windowrule=isfloating:1,appid:^xdg-desktop-portal-kde$
windowrule=isfloating:1,appid:^xdg-desktop-portal-hyprland$
windowrule=isfloating:1,appid:^polkit-gnome-authentication-agent-1$
windowrule=isfloating:1,appid:^hyprpolkitagent$
windowrule=isfloating:1,appid:^CachyOSHello$
windowrule=isfloating:1,appid:^zenity$
windowrule=isfloating:1,appid:^gnome-calculator$
windowrule=isfloating:1,appid:^galculator$
windowrule=isfloating:1,appid:^org\.gnome\.Nautilus$
windowrule=isfloating:1,appid:^xdg-desktop-portal$
windowrule=isfloating:1,appid:^zoom$
windowrule=isfloating:1,appid:^org\.kde\.dragonplayer$
windowrule=isfloating:1,appid:^Signal$
windowrule=isfloating:1,appid:^com\.github\.rafostar\.Clapper$
windowrule=isfloating:1,appid:^app\.drey\.Warp$
windowrule=isfloating:1,appid:^net\.davidotek\.pupgui2$
windowrule=isfloating:1,appid:^yad$
windowrule=isfloating:1,appid:^eog$
windowrule=isfloating:1,appid:^io\.github\.alainm23\.planify$
windowrule=isfloating:1,appid:^io\.gitlab\.theevilskeleton\.Upscaler$
windowrule=isfloating:1,appid:^com\.github\.unrud\.VideoDownloader$
windowrule=isfloating:1,appid:^io\.gitlab\.adhami3310\.Impression$
windowrule=isfloating:1,appid:^io\.missioncenter\.MissionCenter$

# Float by title
windowrule=isfloating:1,title:^Picture-in-Picture$
windowrule=isfloating:1,title:^Picture in picture$
windowrule=isfloating:1,title:^Save File$
windowrule=isfloating:1,title:^Open File$
windowrule=isfloating:1,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$

# Float satty (screenshot annotation)
windowrule=isfloating:1,appid:^satty$

# Gaming tag 5 - floating windows

