# Rendre Tmux conscient des capacités de Kitty (True Color & Italiques)
set -g default-terminal "xterm-kitty"
set -as terminal-overrides ',xterm-kitty:Ms=\E]52;%p1%s;%p2%s\007'

# Définir Fish comme shell par défaut dans Tmux
set-option -g default-shell /usr/bin/fish

# Améliorer le copier-coller (Kitty + Tmux)
set -s set-clipboard on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'

set -g @continuum-restore 'on'

# --- Design & Workflow Svelte ---
# Barre de statut sobre pour ne pas distraire du code
set -g status-style bg=default,fg=white
set -g window-status-current-style fg=magenta,bold

# Raccourci pour diviser l'écran et lancer le serveur Svelte instantanément
bind S split-window -v -p 30 "npm run dev"
