-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

-- Input Remapper : réinjecte le preset « swap-buttons » du trackball Kensington
-- (inversion BTN_RIGHT <-> BTN_SIDE). Équivalent de l'exec-once de Mango dans
-- ~/.config/mango/autostart.conf. Le script retente tant que le service
-- input-remapper / le récepteur USB ne sont pas prêts.
hl.on("hyprland.start", function()
	hl.exec_cmd("/home/loops/.local/bin/input-remapper-autostart.sh")
end)

hl.config({
	scrolling = {
		-- Équivalents Mango WM (layout "scroller")
		direction = "right",                             -- nouvelles fenêtres / défilement vers la droite
		column_width = 0.5,                              -- = scroller_default_proportion (Mango)
		explicit_column_widths = "0.25, 0.5, 0.75, 1.0", -- = scroller_proportion_preset (Mango)
		focus_fit_method = 1,
	},
	input = {
		-- Mango input.conf : xkb_rules_layout=us + xkb_rules_variant=altgr-intl
		kb_layout = "us",
		kb_variant = "altgr-intl",
		numlock_by_default = true,
		-- 2 = focus pointeur détaché du focus clavier : la molette (et le survol) vont à la
		-- fenêtre sous le curseur même si elle n'est pas active, sans lui voler le focus clavier
		-- (comportement Mango/dwl). Avec 0, Hyprland ne donne jamais le focus pointeur à la
		-- fenêtre survolée → impossible de scroller dans une fenêtre non active.
		follow_mouse = 2,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "scrolling",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default", style = "slidevert" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
