[colors]
background = '#303446'
foreground = '#c6d0f5'

cursor_bg = '#eebebe'
cursor_fg = '#303446'
cursor_border = '#eebebe'

selection_bg = '#744f52'
selection_fg = '#c6d0f5'

ansi = ['#292c3c', '#e25a5a', '#57b23e', '#ffd93f', '#f9c4c4', '#ffeeee', '#eebebe', '#423f3f']
brights = ['#cac5c5', '#ff7f7f', '#91ff72', '#ffdc4c', '#ffc6c6', '#ffeeee', '#ffe5e5', '#fff9f9']
