[colors]
background = '#24273a'
foreground = '#cad3f5'

cursor_bg = '#91d7e3'
cursor_fg = '#24273a'
cursor_border = '#91d7e3'

selection_bg = '#245667'
selection_fg = '#cad3f5'

ansi = ['#1e2030', '#ff72a2', '#71e37c', '#fff572', '#7ac9d7', '#245667', '#91d7e3', '#e0eaee']
brights = ['#4c5355', '#ff9fc0', '#a5ffae', '#fff8a5', '#adeef9', '#bef5ff', '#d5f8ff', '#f8fdff']
