-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + CTRL + space")
hl.bind("ALT + CTRL + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"), { description = "Overview (ex Super+O)" })
hl.unbind("SUPER + ALT + 1")
hl.bind("SUPER + ALT + 1", hl.dsp.window.move({ workspace = "1", follow = false }))
hl.unbind("SUPER + ALT + 2")
hl.bind("SUPER + ALT + 2", hl.dsp.window.move({ workspace = "2", follow = false }))
hl.unbind("SUPER + ALT + 3")
hl.bind("SUPER + ALT + 3", hl.dsp.window.move({ workspace = "3", follow = false }))
hl.unbind("SUPER + ALT + 4")
hl.bind("SUPER + ALT + 4", hl.dsp.window.move({ workspace = "4", follow = false }))
hl.unbind("SUPER + ALT + 5")
hl.bind("SUPER + ALT + 5", hl.dsp.window.move({ workspace = "5", follow = false }))
hl.unbind("SUPER + ALT + 6")
hl.bind("SUPER + ALT + 6", hl.dsp.window.move({ workspace = "6", follow = false }))
hl.unbind("SUPER + ALT + 7")
hl.bind("SUPER + ALT + 7", hl.dsp.window.move({ workspace = "7", follow = false }))
hl.unbind("SUPER + ALT + 8")
hl.bind("SUPER + ALT + 8", hl.dsp.window.move({ workspace = "8", follow = false }))
hl.unbind("SUPER + ALT + 9")
hl.bind("SUPER + ALT + 9", hl.dsp.window.move({ workspace = "9", follow = false }))
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.focus({ workspace = "e+1" }))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.focus({ workspace = "e-1" }))
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.focus({ direction = "l" }))
hl.unbind("SUPER + CTRL + A")
hl.bind("SUPER + CTRL + A", hl.dsp.layout("colresize -conf"), { description = "Mango: proportion preset précédent" })
hl.unbind("SUPER + CTRL + D")
hl.bind("SUPER + CTRL + D", hl.dsp.layout("colresize +conf"), { description = "Mango: proportion preset suivant" })
hl.unbind("SUPER + CTRL + left")
hl.bind("SUPER + CTRL + left", hl.dsp.window.move({ monitor = "l" }))
hl.unbind("SUPER + CTRL + right")
hl.bind("SUPER + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.focus({ direction = "r" }))
hl.unbind("SUPER + SHIFT + A")
hl.bind("SUPER + SHIFT + A", hl.dsp.focus({ monitor = "l" }))
hl.unbind("SUPER + SHIFT + D")
hl.bind("SUPER + SHIFT + D", hl.dsp.focus({ monitor = "r" }))
hl.unbind("SUPER + SHIFT + left")
hl.bind("SUPER + SHIFT + left", hl.dsp.focus({ monitor = "l" }))
hl.unbind("SUPER + SHIFT + right")
hl.bind("SUPER + SHIFT + right", hl.dsp.focus({ monitor = "r" }))
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("zen-browser"), { description = "Mango: zen-browser" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"), { description = "Dolphin" })
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("obsidian"), { description = "Obsidian" })
hl.unbind("SUPER + RETURN")
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("ghostty"), { description = "ghostty (ex Super+T)" })
hl.unbind("ALT + TAB")
hl.bind("ALT + TAB", hl.dsp.window.cycle_next(), { description = "Mango: fenêtre suivante" })
hl.unbind("ALT + space")
hl.unbind("Print")
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle fullscreen" })
hl.unbind("SUPER + SHIFT + F")
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"), { description = "Kitty" })
hl.unbind("SUPER + space")
