-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(babbf1)",
			inactive_border = "rgb(737994)",
		},
	},
	group = {
		col = {
			border_active = "rgb(babbf1)",
			border_inactive = "rgb(737994)",
			border_locked_active = "rgb(e78284)",
			border_locked_inactive = "rgb(737994)",
		},
		groupbar = {
			col = {
				active = "rgb(babbf1)",
				inactive = "rgb(737994)",
				locked_active = "rgb(e78284)",
				locked_inactive = "rgb(737994)",
			},
		},
	},
})
