-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-2", mode = "2560x1600@239.999", position = "4161x0", scale = 1, vrr = 1 })
hl.monitor({ output = "", mode = "preferred", position = "1601x0", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "1601x0", scale = 1, vrr = 0 })
hl.monitor({ output = "eDP-1", mode = "1920x1080@60.061", position = "0x179", scale = 1.19921875, vrr = 0 })
