bind=SUPER,r,reload_config
bind=SUPER,comma,spawn,dms ipc call settings focusOrToggle

bind=SUPER+SHIFT,Escape,spawn,dms ipc call processlist focusOrToggle
bind=SUPER,n,spawn,dms ipc call notifications toggle
bind=SUPER,space,spawn,dms ipc call spotlight toggle
bind=SUPER,Super_L,spawn,dms ipc call spotlight toggle
bind=SUPER,v,spawn,dms ipc call clipboard toggle
bind=SUPER,y,spawn,dms ipc call dankdash wallpaper
bind=none,XF86AudioLowerVolume,spawn,dms ipc call audio decrement 5
bind=none,XF86AudioMicMute,spawn,dms ipc call audio micmute # Microphone Mute Toggle
bind=none,XF86AudioMute,spawn,dms ipc call audio mute
bind=none,XF86AudioPlay,spawn,dms ipc call mpris playPause # Media: Play/Pause
bind=none,XF86AudioRaiseVolume,spawn,dms ipc call audio increment 5
bind=none,XF86MonBrightnessDown,spawn,dms ipc call brightness decrement 5
bind=none,XF86MonBrightnessUp,spawn,dms ipc call brightness increment 5
bind=Super,T,spawn,kitty

bind=Super,F,toggleemaximumscreen

bind=Super+CTRL,F,togglefloating
# Window manipulation
mousebind=SUPER,btn_left,moveresize,curmove
#mousebind=,mouse:272,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_forward,resizewin,-10,0
mousebind=super,btn_back,resizewin,0,+10

bind=SUPER+CTRL,z,switch_proportion_preset, previous
bind=SUPER+CTRL,x,switch_proportion_preset, next
#
bind=SUPER+CTRL,l,switch_layout

#Focus & Movement
bind=SUPER,l,focusdir,right
bind=SUPER,h,focusdir,left
bind=SUPER,z,focusstack,prev
bind=SUPER,x,focusstack,next
bind=SUPER,D, toggleoverview
